# Generated by Django 5.2.9 on 2025-12-14 17:42

import b24pysdk.bitrix_api.credentials.bitrix_token
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix24Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('b24_user_id', models.IntegerField()),
                ('is_b24_user_admin', models.BooleanField(default=False)),
                ('member_id', models.CharField(max_length=255)),
                ('is_master_account', models.BooleanField(null=True)),
                ('domain_url', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('application_token', models.CharField(max_length=255, null=True)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True)),
                ('updated_at_utc', models.DateTimeField(auto_now=True)),
                ('application_version', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('refresh_token', models.CharField(max_length=255, null=True)),
                ('expires', models.IntegerField(null=True)),
                ('expires_in', models.IntegerField(null=True)),
                ('current_scope', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'bitrix24account',
                'managed': True,
            },
            bases=(models.Model, b24pysdk.bitrix_api.credentials.bitrix_token.AbstractBitrixToken),
        ),
        migrations.CreateModel(
            name='ApplicationInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True)),
                ('update_at_utc', models.DateTimeField(auto_now=True)),
                ('contact_person_id', models.UUIDField(null=True)),
                ('bitrix_24_partner_contact_person_id', models.UUIDField(null=True)),
                ('bitrix_24_partner_id', models.UUIDField(null=True)),
                ('external_id', models.CharField(max_length=255, null=True)),
                ('portal_license_family', models.CharField(max_length=255)),
                ('portal_users_count', models.IntegerField(null=True)),
                ('application_token', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(null=True)),
                ('status_code', models.JSONField(null=True)),
                ('bitrix_24_account', models.OneToOneField(db_column='bitrix_24_account_id', on_delete=django.db.models.deletion.CASCADE, to='main.bitrix24account')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bitrix_id', models.IntegerField(db_index=True)),
                ('task_id', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50)),
                ('hours', models.FloatField()),
                ('is_billable', models.BooleanField(default=False)),
                ('non_billable_hours', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('task_hierarchy_ids', models.JSONField(default=list)),
                ('task_hierarchy_titles', models.JSONField(default=list)),
                ('date_reflection', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix24_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='main.bitrix24account')),
            ],
            options={
                'db_table': 'timesheet_item',
                'managed': True,
                'unique_together': {('bitrix24_account', 'bitrix_id')},
            },
        ),
    ]
