# Generated by Django 5.2.9 on 2025-12-15 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('status_code', models.IntegerField(null=True)),
                ('duration_ms', models.FloatField(null=True)),
                ('request_body', models.TextField(null=True)),
                ('response_body', models.TextField(null=True)),
                ('error_message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'request_log',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('traceback', models.TextField(null=True)),
            ],
            options={
                'db_table': 'system_log',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
