# Generated by Codex on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_requestlog_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetitem',
            name='source_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
