# Generated by Codex on 2026-04-05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_timesheetitem_source_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('stage', models.CharField(db_index=True, max_length=50)),
                ('manual_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('project_hours_budget', models.FloatField(blank=True, null=True)),
                ('hourly_rate', models.FloatField(default=0.0)),
                ('is_support', models.BooleanField(default=False)),
                ('curator_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('curator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_writeoff_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_writeoff_days', models.IntegerField(default=0)),
                ('stage_updated_at', models.DateTimeField(auto_now=True)),
                ('stage_source', models.CharField(default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix24_account', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='project_cards', to='main.bitrix24account')),
            ],
            options={
                'db_table': 'project_card',
                'managed': True,
                'unique_together': {('bitrix24_account', 'project_id')},
            },
        ),
    ]
