# Generated by Codex on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_projectcard_our_legal_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationinstallation",
            name="support_line_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="applicationinstallation",
            name="support_line_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationinstallation",
            name="support_line_dialog_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applicationinstallation",
            name="support_line_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationinstallation",
            name="support_line_status",
            field=models.CharField(default="not_connected", max_length=50),
        ),
    ]
