# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_applicationinstallation_support_line"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="timesheetitem",
            index=models.Index(fields=["bitrix24_account", "date_reflection"], name="timesheet_acc_date_idx"),
        ),
        migrations.AddIndex(
            model_name="timesheetitem",
            index=models.Index(fields=["bitrix24_account", "employee_id", "date_reflection"], name="timesheet_acc_emp_date_idx"),
        ),
        migrations.AddIndex(
            model_name="timesheetitem",
            index=models.Index(fields=["bitrix24_account", "project_id", "date_reflection"], name="timesheet_acc_proj_date_idx"),
        ),
        migrations.AddIndex(
            model_name="timesheetitem",
            index=models.Index(fields=["bitrix24_account", "project_title", "date_reflection"], name="ts_acc_proj_ttl_dt_idx"),
        ),
        migrations.AddIndex(
            model_name="timesheetitem",
            index=models.Index(fields=["bitrix24_account", "created_at", "bitrix_id"], name="timesheet_acc_created_idx"),
        ),
    ]
