# Generated by Django 5.2.9 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_timesheetitem_query_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(fields=["timestamp"], name="request_log_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(fields=["timestamp"], name="system_log_ts_idx"),
        ),
    ]
