# Generated by Django 4.2.29 on 2026-06-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_timesheetitem_hourly_rate_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='bitrix24_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.bitrix24account'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='bitrix24_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.bitrix24account'),
        ),
        migrations.AlterUniqueTogether(
            name='bitrix24account',
            unique_together={('b24_user_id', 'domain_url')},
        ),
    ]
