# Generated by Django 4.2.29 on 2026-06-10 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_requestlog_bitrix24_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(default='timesheet', max_length=20)),
                ('status', models.CharField(default='running', max_length=20)),
                ('portals_total', models.IntegerField(default=0)),
                ('portals_synced', models.IntegerField(default=0)),
                ('items_synced', models.IntegerField(default=0)),
                ('window_days', models.IntegerField(default=7)),
                ('error_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_run',
                'ordering': ['-started_at'],
                'managed': True,
                'indexes': [models.Index(fields=['started_at'], name='sync_run_started_idx')],
            },
        ),
    ]
