# Generated by Django 4.2.29 on 2026-06-10 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_syncrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=255, unique=True)),
                ('domain_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True)),
                ('updated_at_utc', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portal',
                'managed': True,
                'indexes': [models.Index(fields=['member_id'], name='portal_member_id_idx')],
            },
        ),
        migrations.AddField(
            model_name='bitrix24account',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='main.portal'),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cards', to='main.portal'),
        ),
        migrations.AddField(
            model_name='timesheetitem',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='main.portal'),
        ),
    ]
