# Generated by Django 4.2.30 on 2026-07-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_seed_portals_from_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix24account',
            name='last_timesheet_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
