# Generated by Django 4.2.30 on 2026-07-27 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_bitrix24account_last_timesheet_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bitrix_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix24_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='main.bitrix24account')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='main.portal')),
            ],
            options={
                'db_table': 'portal_user',
                'managed': True,
                'indexes': [models.Index(fields=['bitrix24_account', 'active'], name='portal_user_acc_active_idx')],
                'unique_together': {('bitrix24_account', 'bitrix_id')},
            },
        ),
    ]
