# Generated by Django 4.2.30 on 2026-07-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_portaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix24account',
            name='sync_disabled_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitrix24account',
            name='sync_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitrix24account',
            name='sync_failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
