# Generated by Django 6.1 on 2026-08-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_bitrix24account_sync_disabled_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix24account',
            name='admin_flag_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
