# Generated by Django 6.1 on 2026-08-31 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_bitrix24account_admin_flag_checked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bitrix_id', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('group_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix24_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_tasks', to='main.bitrix24account')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_tasks', to='main.portal')),
            ],
            options={
                'db_table': 'portal_task',
                'managed': True,
                'indexes': [models.Index(fields=['bitrix24_account', 'group_id'], name='portal_task_acc_group_idx')],
                'unique_together': {('bitrix24_account', 'bitrix_id')},
            },
        ),
    ]
