# Generated by Django 6.1 on 2026-08-31 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_portaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('closed_at', models.DateTimeField()),
                ('closed_by', models.CharField(blank=True, default='', max_length=50)),
                ('closed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_by', models.CharField(blank=True, default='', max_length=50)),
                ('reopened_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix24_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_periods', to='main.bitrix24account')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to='main.portal')),
            ],
            options={
                'db_table': 'closed_period',
                'ordering': ['-year', '-month'],
                'managed': True,
                'indexes': [models.Index(fields=['bitrix24_account', 'year', 'month'], name='closed_period_acc_ym_idx')],
                'unique_together': {('bitrix24_account', 'year', 'month')},
            },
        ),
    ]
