# Generated by Django 5.2.17 on 2026-09-05 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_closedperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneCExportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('sending_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ok', 'Принято'), ('partial', 'Принято частично'), ('failed', 'Не принято')], default='failed', max_length=20)),
                ('sent_rows', models.IntegerField(default=0)),
                ('accepted', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('documents', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('message', models.TextField(blank=True, default='')),
                ('started_by', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bitrix24_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_c_exports', to='main.bitrix24account')),
            ],
            options={
                'db_table': 'one_c_export_run',
                'ordering': ('-created_at',),
                'managed': True,
            },
        ),
    ]
