# Generated by Django 6.1.1 on 2026-09-12 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_closedperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='issued', max_length=16)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('company_id', models.CharField(blank=True, default='', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('our_company_id', models.CharField(blank=True, default='', max_length=50)),
                ('our_company_name', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('vat_mode', models.CharField(default='included', max_length=16)),
                ('vat_rate', models.FloatField(default=0.0)),
                ('total_hours', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('grouping', models.CharField(default='project', max_length=16)),
                ('filter_snapshot', models.JSONField(blank=True, default=dict)),
                ('crm_entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('crm_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('act_document_id', models.CharField(blank=True, default='', max_length=50)),
                ('act_number', models.CharField(blank=True, default='', max_length=100)),
                ('act_download_url', models.TextField(blank=True, default='')),
                ('act_public_url', models.TextField(blank=True, default='')),
                ('act_pdf_url', models.TextField(blank=True, default='')),
                ('act_error', models.TextField(blank=True, default='')),
                ('created_by_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_id', models.CharField(blank=True, default='', max_length=50)),
                ('cancelled_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('bitrix24_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_documents', to='main.bitrix24account')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_documents', to='main.portal')),
            ],
            options={
                'db_table': 'billing_document',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BillingLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, default='', max_length=50)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('hours', models.FloatField(default=0.0)),
                ('rate', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('sort', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='main.billingdocument')),
            ],
            options={
                'db_table': 'billing_line',
                'ordering': ['sort', 'id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BillingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timesheet_bitrix_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.CharField(blank=True, default='', max_length=50)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_reflection', models.DateTimeField(blank=True, null=True)),
                ('hours', models.FloatField(default=0.0)),
                ('rate_snapshot', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('project_id', models.CharField(blank=True, default='', max_length=50)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('task_id', models.CharField(blank=True, default='', max_length=50)),
                ('task_title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('bitrix24_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_entries', to='main.bitrix24account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.billingdocument')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_entries', to='main.portal')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='main.billingline')),
            ],
            options={
                'db_table': 'billing_entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortalFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('state', models.CharField(default='off', max_length=16)),
                ('trial_until', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix24_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_features', to='main.bitrix24account')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_features', to='main.portal')),
            ],
            options={
                'db_table': 'portal_feature',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='billingdocument',
            index=models.Index(fields=['bitrix24_account', 'status'], name='billing_doc_acc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdocument',
            index=models.Index(fields=['bitrix24_account', 'company_id'], name='billing_doc_acc_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdocument',
            index=models.Index(fields=['bitrix24_account', 'period_from'], name='billing_doc_acc_period_idx'),
        ),
        migrations.AddIndex(
            model_name='billingentry',
            index=models.Index(fields=['bitrix24_account', 'timesheet_bitrix_id'], name='billing_entry_acc_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('bitrix24_account', 'timesheet_bitrix_id'), name='billing_entry_one_active_per_timesheet'),
        ),
        migrations.AddIndex(
            model_name='portalfeature',
            index=models.Index(fields=['code', 'state'], name='portal_feature_code_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portalfeature',
            unique_together={('bitrix24_account', 'code')},
        ),
    ]
