# Generated by Django 6.1.1 on 2026-09-12 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_portal_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProInvoiceSequence',
            fields=[
                ('prefix', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'pro_invoice_sequence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortalBillingCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_code', to='main.portal')),
            ],
            options={
                'db_table': 'portal_billing_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by_id', models.CharField(blank=True, default='', max_length=50)),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('requested_by_admin', models.BooleanField(default=False)),
                ('domain_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('member_id_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('portal_code', models.CharField(max_length=6)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.CharField(blank=True, default='', max_length=254)),
                ('contact_cc', models.CharField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('payer_type', models.CharField(default='org', max_length=8)),
                ('payer_inn', models.CharField(max_length=12)),
                ('payer_kpp', models.CharField(blank=True, default='', max_length=9)),
                ('payer_name', models.CharField(max_length=500)),
                ('payer_address', models.CharField(blank=True, default='', max_length=500)),
                ('payer_company_id', models.CharField(blank=True, default='', max_length=50)),
                ('months', models.PositiveSmallIntegerField()),
                ('price_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_mode', models.CharField(max_length=16)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sequence_number', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_purpose', models.CharField(max_length=210)),
                ('offer_accepted_at', models.DateTimeField()),
                ('status', models.CharField(db_index=True, default='draft', max_length=16)),
                ('crm_company_id', models.CharField(blank=True, default='', max_length=50)),
                ('crm_deal_id', models.CharField(blank=True, default='', max_length=50)),
                ('crm_invoice_id', models.CharField(blank=True, default='', max_length=50)),
                ('crm_document_id', models.CharField(blank=True, default='', max_length=50)),
                ('crm_pdf_url', models.TextField(blank=True, default='')),
                ('crm_error', models.TextField(blank=True, default='')),
                ('crm_attempts', models.PositiveIntegerField(default=0)),
                ('crm_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('crm_sent_at', models.DateTimeField(blank=True, null=True)),
                ('crm_cancel_synced_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('paid_by', models.CharField(blank=True, default='', max_length=255)),
                ('pro_paid_until', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, default='', max_length=255)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pro_requests', to='main.portal')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='main.prorequest')),
                ('requested_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_requests', to='main.bitrix24account')),
            ],
            options={
                'db_table': 'pro_request',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['portal', 'status'], name='pro_request_portal_status_idx'), models.Index(fields=['portal_code'], name='pro_request_code_idx'), models.Index(fields=['payer_inn'], name='pro_request_inn_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'sent'])), fields=('portal',), name='pro_request_one_open_per_portal')],
            },
        ),
    ]
