# Generated by Django 6.1.1 on 2026-09-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_portal_permission_matrix'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billingentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('portal__isnull', False)), fields=('portal', 'timesheet_bitrix_id'), name='billing_entry_one_active_per_timesheet_per_portal'),
        ),
    ]
