# Generated by Django 6.1.1 on 2026-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_billing_entry_portal_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorequest',
            name='crm_task_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
